version: '3'
services:
  redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker-data:/data
    command:
      - redis-server
      - --appendonly
      - "yes"
